// World Labs 与 Tripo 的付费调用。状态记在 outputs/left-generation.json 和 outputs/left-river-world.json。
// 当前页面用的是已经下载的纯河岸世界和近景模型。再跑这些函数会扣费。
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {reconstruction} from './data/reconstruction.mjs';

const out=path.join(import.meta.dirname,'outputs');
const stateFile=path.join(out,'left-generation.json');
const worldBase='https://api.worldlabs.ai/marble/v1';
const tripoBase='https://openapi.tripo3d.ai/v3';
let lock=Promise.resolve();
async function exclusive(fn){let previous=lock,release;lock=new Promise(resolve=>release=resolve);await previous;try{return await fn();}finally{release();}}
async function load(){try{return JSON.parse(await readFile(stateFile,'utf8'));}catch{return {schemaVersion:1,siteId:'left',world:null,object:null};}}
async function save(state){await mkdir(out,{recursive:true});await writeFile(stateFile,JSON.stringify(state,null,2),{mode:0o600});}
async function request(url,options){const response=await fetch(url,{...options,signal:AbortSignal.timeout(30000),redirect:'error'});const data=await response.json().catch(()=>({}));if(!response.ok){let e=new Error(`服务拒绝请求（HTTP ${response.status}）${response.status===402?'：账户额度不足':''}`);e.status=502;throw e;}return data;}
function worldHeaders(){if(!process.env.WORLDLABS_API_KEY)throw new Error('World Labs 密钥未配置');return {'WLT-Api-Key':process.env.WORLDLABS_API_KEY};}
function tripoHeaders(){if(!process.env.TRIPO_API_KEY)throw new Error('Tripo 密钥未配置');return {Authorization:`Bearer ${process.env.TRIPO_API_KEY}`};}
async function downloadAsset(url,name,maxBytes){if(!url)return null;const parsed=new URL(url);if(parsed.protocol!=='https:')throw new Error('资源地址不安全');const response=await fetch(url,{signal:AbortSignal.timeout(60000),redirect:'follow'});if(!response.ok)throw new Error('生成资源下载失败');const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length>maxBytes)throw new Error('生成资源超过本地大小限制');await writeFile(path.join(out,name),bytes,{mode:0o600});return `/generated/${name}`;}
async function uploadConceptImage(){
  const name='left-phase1-concept-v2.png',bytes=await readFile(path.join(out,name));
  const prepared=await request(`${worldBase}/media-assets:prepare_upload`,{method:'POST',headers:{...worldHeaders(),'Content-Type':'application/json'},body:JSON.stringify({file_name:name,kind:'image',extension:'png'})});
  const id=prepared.media_asset?.media_asset_id||prepared.media_asset?.id,upload=prepared.upload_info;
  if(!id||!upload?.upload_url||upload.upload_method!=='PUT'||new URL(upload.upload_url).protocol!=='https:')throw new Error('World Labs 未返回有效的图像上传地址');
  const response=await fetch(upload.upload_url,{method:'PUT',headers:upload.required_headers||{},body:bytes,signal:AbortSignal.timeout(120000),redirect:'error'});
  if(!response.ok)throw new Error(`概念图上传失败（HTTP ${response.status}）`);
  return id;
}
async function uploadConceptImageToTripo(){
  const bytes=await readFile(path.join(out,'left-phase1-concept-v2.png'));
  const form=new FormData();form.set('file',new Blob([bytes],{type:'image/png'}),'left-phase1-concept-v2.png');
  const data=await request(`${tripoBase}/files`,{method:'POST',headers:tripoHeaders(),body:form});
  if(data.code!==0||!data.data?.file_token)throw new Error('Tripo 未返回图像文件令牌');
  return data.data.file_token;
}
export function plan(){return reconstruction;}
export async function state(){return load();}
export async function nearfieldState(){let tasks;try{tasks=JSON.parse(await readFile(path.join(out,'nearfield','tasks.json'),'utf8'));}catch{tasks={items:{}};}const house=tasks.items?.house,houseV2=tasks.items?.houseV2,grass=tasks.items?.grass,light=tasks.items?.grassLight,ground=tasks.items?.ground,potV2=tasks.items?.potV2,branches=tasks.items?.branches,boneTools=tasks.items?.boneTools,refuse=tasks.items?.refuse,seatedGuide=tasks.items?.seatedGuide;const model=item=>item?.status==='ready'?item.modelUrl:null;return {status:house?.status==='ready'&&grass?.status==='ready'&&light?.status==='ready'?'ready':'preparing',siteId:'left',phase:'一期后段',assets:{house:model(house),grass:model(grass),grassLight:model(light),groundTexture:existsSync(path.join(out,'nearfield','ground-texture-v1.png'))?'/generated/nearfield/ground-texture-v1.png':null,groundModel:model(ground),pot:model(potV2),branches:model(branches),boneTools:model(boneTools),refuse:model(refuse),seatedGuide:model(seatedGuide)},tasks:Object.fromEntries(Object.entries({house,houseV2,grass,grassLight:light,ground,potV2,branches,boneTools,refuse,seatedGuide}).map(([name,item])=>[name,item?.status||'not_started'])),creditsConsumed:[house,houseV2,grass,light,ground,potV2,branches,boneTools,refuse,seatedGuide].reduce((n,item)=>n+(item?.creditsConsumed||0),0),experimentalHouse:{status:houseV2?.status||'not_started',deployed:false,reason:'新模型将屋体与土台烘成单一网格，未通过当前地形衔接验收'},note:'上部房屋、人物与草种属推测，地面材质为视觉示意；二期石龙和无证据床具不进入一期场景。'};}
export async function emptyWorldState(){
  const read=async name=>{try{return JSON.parse(await readFile(path.join(out,name),'utf8'));}catch{return {status:'not_started'};}};
  const plus=await read('left-empty-world.json'),standard=await read('left-empty-world-standard.json'),distant=await read('left-empty-world-distant.json');
  const value=plus.status==='ready'?plus:distant.status==='ready'?distant:standard.status==='ready'?standard:distant.status==='running'?distant:plus.status==='running'?plus:standard.status!=='not_started'?standard:plus;
  return {status:value.status,model:value.model||null,thumbnail:value.thumbnail||null,pano:value.pano||null,splat:value.splat||null,collider:value.collider||null,metricScaleFactor:value.metricScaleFactor||null,groundPlaneOffset:value.groundPlaneOffset??null,marbleUrl:value.marbleUrl||null,costCredits:value.costCredits??null,sourceImage:value.sourceImage||null,error:value.status==='failed'?value.error:null,plusStatus:plus.status,standardStatus:standard.status,distantStatus:distant.status};
}
export async function riverWorldState(){
  let result;try{result=JSON.parse(await readFile(path.join(out,'left-river-world.json'),'utf8'));}catch{return {status:'not_started',sourceImage:'/generated/left-river-environment-v1.png'};}
  const {status,model,worldId,thumbnail,pano,splat,collider,metricScaleFactor,groundPlaneOffset,marbleUrl,costCredits,sourceImage,error,progress}=result;
  return {status,model,worldId,thumbnail,pano,splat,collider,metricScaleFactor,groundPlaneOffset,marbleUrl,costCredits,sourceImage,error:status==='failed'?error:null,progress:status==='running'?progress:null};
}
export async function startWorld(){return exclusive(async()=>{let s=await load();if(s.world?.operationId||s.world?.status==='ready')return s;const body={display_name:'左家山一期 · 考古证据约束场景',model:reconstruction.world.model,permission:{public:false},world_prompt:{type:'text',text_prompt:reconstruction.world.prompt}};let data=await request(`${worldBase}/worlds:generate`,{method:'POST',headers:{...worldHeaders(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(!data.operation_id)throw new Error('World Labs 未返回任务编号');s.world={status:'running',operationId:data.operation_id,startedAt:new Date().toISOString(),model:body.model,inputType:'text',estimatedCredits:reconstruction.world.estimatedCredits};await save(s);return s;});}
export async function refreshWorld(){return exclusive(async()=>{let s=await load(),w=s.world;if(!w?.operationId||['ready','failed'].includes(w.status))return s;let op=await request(`${worldBase}/operations/${encodeURIComponent(w.operationId)}`,{headers:worldHeaders()});w.progress=op.metadata?.progress?.description||op.metadata?.progress?.status||'处理中';if(op.done){if(op.error){w.status='failed';w.error=op.error.message||'生成失败';}else{let world=op.response?.world||op.response;let id=world?.world_id||world?.id||op.metadata?.world_id;if(!id)throw new Error('World Labs 已完成，但未返回世界编号');let full=await request(`${worldBase}/worlds/${encodeURIComponent(id)}`,{headers:worldHeaders()});world=full.world||full;w.worldId=id;w.marbleUrl=world.world_marble_url||null;w.costCredits=op.cost?.total_credits??null;w.caption=world.assets?.caption||'';w.status='ready';w.completedAt=new Date().toISOString();for(let [url,name,max] of [[world.assets?.thumbnail_url,'left-world-thumb.jpg',10e6],[world.assets?.imagery?.pano_url,'left-world-pano.jpg',30e6],[world.assets?.splats?.spz_urls?.['100k'],'left-world-100k.spz',30e6]]){try{let local=await downloadAsset(url,name,max);if(local)w[name.includes('thumb')?'thumbnail':name.includes('pano')?'pano':'splat']=local;}catch(e){w.assetWarning=e.message;}}}}await save(s);return s;});}
export async function startImageWorld(){return exclusive(async()=>{let s=await load();if(s.imageWorld?.operationId||s.imageWorld?.status==='ready')return s;const mediaAssetId=await uploadConceptImage();const body={display_name:'左家山一期 · 图像约束场景 v2',model:reconstruction.imageWorld.model,permission:{public:false},world_prompt:{type:'image',image_prompt:{source:'media_asset',media_asset_id:mediaAssetId},text_prompt:reconstruction.imageWorld.prompt}};const data=await request(`${worldBase}/worlds:generate`,{method:'POST',headers:{...worldHeaders(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(!data.operation_id)throw new Error('World Labs 未返回任务编号');s.imageWorld={status:'running',operationId:data.operation_id,mediaAssetId,startedAt:new Date().toISOString(),model:body.model,inputType:'image',sourceImage:reconstruction.imageWorld.conceptImage,estimatedCredits:reconstruction.imageWorld.estimatedCredits};await save(s);return s;});}
export async function refreshImageWorld(){return exclusive(async()=>{let s=await load(),w=s.imageWorld;if(!w?.operationId||w.status==='failed')return s;if(w.status==='ready'){if(!w.highResSplat&&w.worldId){const full=await request(`${worldBase}/worlds/${encodeURIComponent(w.worldId)}`,{headers:worldHeaders()});const url=(full.world||full).assets?.splats?.spz_urls?.['500k'];try{w.highResSplat=await downloadAsset(url,'left-world-v2-500k.spz',80e6);if(w.highResSplat){w.splat=w.highResSplat;w.splatQuality='500k';}}catch(e){w.assetWarning=e.message;}await save(s);}return s;}const op=await request(`${worldBase}/operations/${encodeURIComponent(w.operationId)}`,{headers:worldHeaders()});w.progress=op.metadata?.progress?.description||op.metadata?.progress?.status||'处理中';if(op.done){if(op.error){w.status='failed';w.error=op.error.message||'生成失败';}else{let world=op.response?.world||op.response;const id=world?.world_id||world?.id||op.metadata?.world_id;if(!id)throw new Error('World Labs 已完成，但未返回世界编号');const full=await request(`${worldBase}/worlds/${encodeURIComponent(id)}`,{headers:worldHeaders()});world=full.world||full;w.worldId=id;w.marbleUrl=world.world_marble_url||null;w.costCredits=op.cost?.total_credits??null;w.caption=world.assets?.caption||'';w.status='ready';w.completedAt=new Date().toISOString();for(const [url,name,max] of [[world.assets?.thumbnail_url,'left-world-v2-thumb.jpg',10e6],[world.assets?.imagery?.pano_url,'left-world-v2-pano.jpg',30e6],[world.assets?.splats?.spz_urls?.['100k'],'left-world-v2-100k.spz',30e6]]){try{const local=await downloadAsset(url,name,max);if(local)w[name.includes('thumb')?'thumbnail':name.includes('pano')?'pano':'splat']=local;}catch(e){w.assetWarning=e.message;}}}}await save(s);return s;});}
export async function startPlusWorld(){return exclusive(async()=>{const s=await load();if(s.plusWorld?.operationId||s.plusWorld?.status==='ready')return s;if(s.imageWorld?.status!=='ready'||!s.imageWorld.mediaAssetId)throw new Error('缺少标准版图像任务，无法确保使用同一张输入图片');const body={display_name:'左家山一期 · Marble 1.1 Plus 对比',model:reconstruction.plusWorld.model,permission:{public:false},world_prompt:{type:'image',image_prompt:{source:'media_asset',media_asset_id:s.imageWorld.mediaAssetId},text_prompt:reconstruction.imageWorld.prompt}};const data=await request(`${worldBase}/worlds:generate`,{method:'POST',headers:{...worldHeaders(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(!data.operation_id)throw new Error('World Labs 未返回 Plus 任务编号');s.plusWorld={status:'running',operationId:data.operation_id,mediaAssetId:s.imageWorld.mediaAssetId,startedAt:new Date().toISOString(),model:body.model,inputType:'image',sourceImage:reconstruction.imageWorld.conceptImage,comparisonBaselineWorldId:s.imageWorld.worldId,estimatedCreditsMin:reconstruction.plusWorld.estimatedCreditsMin,estimatedCreditsMax:reconstruction.plusWorld.estimatedCreditsMax};await save(s);return s;});}
export async function refreshPlusWorld(){return exclusive(async()=>{const s=await load(),w=s.plusWorld;if(!w?.operationId||['ready','failed'].includes(w.status))return s;const op=await request(`${worldBase}/operations/${encodeURIComponent(w.operationId)}`,{headers:worldHeaders()});w.progress=op.metadata?.progress?.description||op.metadata?.progress?.status||'处理中';if(op.done){if(op.error){w.status='failed';w.error=op.error.message||'生成失败';}else{let world=op.response?.world||op.response;const id=world?.world_id||world?.id||op.metadata?.world_id;if(!id)throw new Error('World Labs 已完成，但未返回 Plus 世界编号');const full=await request(`${worldBase}/worlds/${encodeURIComponent(id)}`,{headers:worldHeaders()});world=full.world||full;w.worldId=id;w.marbleUrl=world.world_marble_url||null;w.costCredits=op.cost?.total_credits??null;w.caption=world.assets?.caption||'';w.status='ready';w.completedAt=new Date().toISOString();for(const [url,name,field,max] of [[world.assets?.thumbnail_url,'left-world-plus-thumb.jpg','thumbnail',10e6],[world.assets?.imagery?.pano_url,'left-world-plus-pano.jpg','pano',40e6],[world.assets?.splats?.spz_urls?.['500k'],'left-world-plus-500k.spz','splat',80e6]]){try{const local=await downloadAsset(url,name,max);if(local)w[field]=local;}catch(e){w.assetWarning=e.message;}}w.splatQuality=w.splat?'500k':null;}}await save(s);return s;});}
export async function startObject(){return exclusive(async()=>{let s=await load();if(s.object?.taskId||s.object?.status==='ready')return s;let body={prompt:reconstruction.object.prompt,model:reconstruction.object.model,texture:true,pbr:true,texture_quality:'standard',face_limit:40000};let data=await request(`${tripoBase}/generation/text-to-model`,{method:'POST',headers:{...tripoHeaders(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(data.code!==0||!data.data?.task_id)throw new Error('Tripo 未接受生成任务');s.object={status:'running',taskId:data.data.task_id,startedAt:new Date().toISOString(),model:body.model,estimatedCredits:reconstruction.object.estimatedCredits};await save(s);return s;});}
export async function refreshObject(){return exclusive(async()=>{let s=await load(),o=s.object;if(!o?.taskId||['ready','failed'].includes(o.status))return s;let result=await request(`${tripoBase}/tasks/${encodeURIComponent(o.taskId)}`,{headers:tripoHeaders()});let data=result.data;if(result.code!==0||!data)throw new Error('Tripo 状态查询失败');o.progress=data.progress||0;if(['failed','cancelled','banned'].includes(data.status)){o.status='failed';o.error=data.error_message||data.status;}else if(data.status==='success'){o.creditsConsumed=data.credits_consumed??null;o.completedAt=new Date().toISOString();try{o.modelUrl=await downloadAsset(data.output?.model_url,'left-cylindrical-pot.glb',80e6);o.preview=await downloadAsset(data.output?.rendered_image_url,'left-cylindrical-pot.png',15e6);o.status=o.modelUrl?'ready':'failed';if(!o.modelUrl)o.error='生成成功但未取得 GLB 模型';}catch(e){o.status='failed';o.error=e.message;}}await save(s);return s;});}
export async function startTripoScene(){return exclusive(async()=>{const s=await load();if(s.tripoScene?.taskId||s.tripoScene?.status==='ready')return s;const fileToken=await uploadConceptImageToTripo();const body={input:fileToken,model:'v3.1-20260211',texture:true,pbr:true,texture_quality:'standard',orientation:'align_image',face_limit:200000};const result=await request(`${tripoBase}/generation/image-to-model`,{method:'POST',headers:{...tripoHeaders(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(result.code!==0||!result.data?.task_id)throw new Error('Tripo 未接受场景模型任务');s.tripoScene={status:'running',taskId:result.data.task_id,startedAt:new Date().toISOString(),inputType:'image-to-model',sourceImage:'/generated/left-phase1-concept-v2.png',model:body.model,estimatedCredits:30,note:'整幅景观输入单体模型接口；仅作能力试验，不是可漫游世界'};await save(s);return s;});}
export async function refreshTripoScene(){return exclusive(async()=>{const s=await load(),o=s.tripoScene;if(!o?.taskId||['ready','failed'].includes(o.status))return s;const result=await request(`${tripoBase}/tasks/${encodeURIComponent(o.taskId)}`,{headers:tripoHeaders()});const data=result.data;if(result.code!==0||!data)throw new Error('Tripo 场景任务状态查询失败');o.progress=data.progress||0;if(['failed','cancelled','banned'].includes(data.status)){o.status='failed';o.error=data.error_message||data.status;}else if(data.status==='success'){o.creditsConsumed=data.credits_consumed??null;o.completedAt=new Date().toISOString();try{o.modelUrl=await downloadAsset(data.output?.model_url,'left-tripo-scene.glb',100e6);o.preview=await downloadAsset(data.output?.rendered_image_url,'left-tripo-scene.png',20e6);o.status=o.modelUrl?'ready':'failed';if(!o.modelUrl)o.error='任务成功但没有返回 GLB 模型';}catch(e){o.status='failed';o.error=e.message;}}await save(s);return s;});}
export async function asset(name){
  const comparison={'left-river-environment-v1.png':'image/png','left-river-world-thumb.jpg':'image/jpeg','left-river-world-pano.jpg':'image/jpeg','left-river-world-splat.spz':'application/octet-stream','left-river-world-collider.glb':'model/gltf-binary','left-phase1-empty-nearfield-v1.png':'image/png','left-phase1-empty-nearfield-v2.png':'image/png','left-empty-world-thumb.jpg':'image/jpeg','left-empty-world-pano.jpg':'image/jpeg','left-empty-world-splat.spz':'application/octet-stream','left-empty-world-collider.glb':'model/gltf-binary','left-empty-world-standard-thumb.jpg':'image/jpeg','left-empty-world-standard-pano.jpg':'image/jpeg','left-empty-world-standard-splat.spz':'application/octet-stream','left-empty-world-standard-collider.glb':'model/gltf-binary','left-empty-world-distant-thumb.jpg':'image/jpeg','left-empty-world-distant-pano.jpg':'image/jpeg','left-empty-world-distant-splat.spz':'application/octet-stream','left-empty-world-distant-collider.glb':'model/gltf-binary'};
  const allowed={'left-world-thumb.jpg':'image/jpeg','left-world-pano.jpg':'image/jpeg','left-world-100k.spz':'application/octet-stream','left-world-v2-thumb.jpg':'image/jpeg','left-world-v2-pano.jpg':'image/jpeg','left-world-v2-100k.spz':'application/octet-stream','left-world-v2-500k.spz':'application/octet-stream','left-world-plus-thumb.jpg':'image/jpeg','left-world-plus-pano.jpg':'image/jpeg','left-world-plus-500k.spz':'application/octet-stream','left-world-plus-collider.glb':'model/gltf-binary','left-phase1-concept-v2.png':'image/png','left-cylindrical-pot.glb':'model/gltf-binary','left-cylindrical-pot.png':'image/png','nearfield/house-reference-v1.png':'image/png','nearfield/ground-texture-v1.png':'image/png','nearfield/grass-dark-reference-v1.png':'image/png','nearfield/grass-light-reference-v1.png':'image/png','nearfield/house-v1.glb':'model/gltf-binary','nearfield/house-preview-v1.png':'image/png','nearfield/ground-v1.glb':'model/gltf-binary','nearfield/ground-preview-v1.png':'image/png','nearfield/grass-v1.glb':'model/gltf-binary','nearfield/grass-preview-v1.png':'image/png','nearfield/grassLight-v1.glb':'model/gltf-binary','nearfield/grassLight-preview-v1.png':'image/png'};
  for(const item of ['potV2','branches','boneTools','refuse','seatedGuide']){allowed[`nearfield/${item}-v1.glb`]='model/gltf-binary';allowed[`nearfield/${item}-preview-v1.png`]='image/png';}
  allowed['rigging/standingGuide-rigged-v1.glb']='model/gltf-binary';
  const mime=comparison[name]||allowed[name];if(!mime||!existsSync(path.join(out,name)))return null;return {mime,bytes:await readFile(path.join(out,name))};
}
