// Shared copy for the linked preview. Chinese pages stay as published.
// English is applied in the browser when the intro language is English.
export const exact = {
  "长春市": "Changchun",
  "吉林市": "Jilin City",
  "四平市": "Siping",
  "辽源市": "Liaoyuan",
  "通化市": "Tonghua",
  "白山市": "Baishan",
  "松原市": "Songyuan",
  "白城市": "Baicheng",
  "延边朝鲜族自治州": "Yanbian Korean Autonomous Prefecture",
  "旧石器时代": "Paleolithic",
  "石器里的文明曙光": "First light of civilization in stone",
  "远古人类 · 打制石器": "Early humans · chipped stone",
  "从榆树平原到长白山地，寻找吉林先民留下的第一批生活痕迹。": "From the Yushu plain to the Changbai mountains, looking for the first traces of life left in Jilin.",
  "王府屯": "Wangfutun",
  "前郭尔罗斯蒙古族自治县": "Qian Gorlos Mongol Autonomous County",
  "年代尚待研究确定": "The date still needs research",
  "位于前郭尔罗斯蒙古族自治县哈拉毛都乡。点位用该县中心，不是乡政府的位置。年代尚待研究确定。": "In Halamodu Township, Qian Gorlos. The dot is the county center, not the township seat. The date still needs research.",
  "榆树人": "Yushu finds",
  "榆树市": "Yushu",
  "旧石器晚期遗存": "Late Paleolithic remains",
  "位于榆树市秀水镇周家油坊。点位用榆树市中心。旧石器晚期，距今大约 3 到 7 万年，不同材料的口径并不一致。": "At Zhoujia Youfang, Xiushui Town, Yushu. The dot is the city center. Late Paleolithic, roughly 30,000 to 70,000 years ago. The published ranges do not agree.",
  "寿山仙人洞": "Shoushan Xianrendong",
  "桦甸市": "Huadian",
  "洞穴、石器与动物骨骼": "Cave, stone tools, and animal bone",
  "资料记载距今约 2 万至 5 万年。": "Published dates fall around 20,000 to 50,000 years ago.",
  "安图人": "Antu finds",
  "安图县": "Antu County",
  "洞穴、石骨角工具": "Cave, stone, bone, and antler tools",
  "资料记载距今约 2.66 万年，遗址位于石门山南坡。": "Published date about 26,600 years ago. The site is on the south slope of Shimenshan.",
  "石人沟 / 大洞": "Shirengou / Dadong",
  "和龙市": "Helong",
  "黑曜石、石叶与细石叶": "Obsidian, blades, and microblades",
  "两处不同遗址，本版按和龙区域合并展示。": "Two different sites, shown together here as the Helong area.",
  "新石器时代": "Neolithic",
  "沿着水系安家": "Settling along the rivers",
  "氏族社会 · 定居生活": "Clan society · settled life",
  "房屋、陶器、玉器和粮食加工工具，讲述农业与渔猎并存的生活。": "Houses, pottery, jade, and grain-processing tools, from a life of farming beside fishing and hunting.",
  "洮北区": "Taobei District",
  "玉鱼、骨柄石刃刀": "Jade fish and bone-handled stone knives",
  "资料记载位于白城市西郊。": "Published location: the western outskirts of Baicheng.",
  "聚宝山": "Jubaoshan",
  "镇赉县": "Zhenlai County",
  "玉环、陶片与渔猎遗存": "Jade rings, potsherds, and fishing and hunting remains",
  "《考古》1998年第6期把聚宝山记在镇赉。点位用镇赉县中心，具体地点仍待核对。": "Kaogu 1998, no. 6, places Jubaoshan in Zhenlai. The dot is the county center. The exact spot is still unchecked.",
  "左家山": "Zuojia Shan",
  "农安县": "Nong'an County",
  "石灰岩石龙、筒形罐与钵": "Limestone dragon, cylindrical jars, and bowls",
  "房址为方形或圆角长方形，有柱洞、门道和灶。二期有石灰岩质石龙。陶器以筒形罐、钵为主，也有碗、斜口器、器座、杯、纺轮，之字纹常见。点位用农安县中心。": "House floors are square or rounded rectangles, with postholes, an entry, and a hearth. Phase II has a limestone dragon. Pottery is mostly cylindrical jars and bowls, also dishes, angled-mouth vessels, stands, cups, and spindle whorls. Zigzag impressions are common. The dot is the Nong'an county center.",
  "腰岭子": "Yaolingzi",
  "九台区": "Jiutai District",
  "半地穴房址、陶石器": "Pit houses, pottery, and stone tools",
  "位于长春市九台区西营城镇西部、石头口门村北。点位用九台区中心。长岭腰井子是另一处遗址。": "West of Xiyingcheng Town, Jiutai, Changchun, north of Shitoukoumen village. The dot is the Jiutai center. Changling Yaojingzi is a different site.",
  "元宝沟": "Yuanbaogou",
  "新石器遗存": "Neolithic remains",
  "位于农安县巴吉垒乡。点位用农安县中心。左家山也用这个县中心，两个圆点在画面上稍微分开。": "In Bajilei Township, Nong'an. The dot is the county center. Zuojia Shan uses that center too, so the two dots are drawn slightly apart.",
  "大六道沟": "Daliudaogou",
  "珲春市": "Hunchun",
  "位于珲春市春化镇，大约距今 4000 年。点位用珲春市中心。临江另有六道沟冶铜遗址，两处要分开看。": "In Chunhua Town, Hunchun, about 4,000 years ago. The dot is the city center. Linjiang has a separate Liudaogou copper site. Keep them apart.",
  "新石器晚期": "Late Neolithic",
  "聚落逐渐成形": "Settlements take shape",
  "兴城二期 · 聚落发展": "Xingcheng phase II · a growing settlement",
  "在图们江流域，房址与石骨陶器呈现更稳定的聚落。兴城一期和二期都属新石器。": "Along the Tumen River, houses and stone, bone, and pottery show a more stable settlement. Xingcheng phases I and II are both Neolithic.",
  "半地穴房址、陶器": "Pit houses and pottery",
  "《和龙兴城》里，一期和二期都是新石器，青铜时代要到三至五期的兴城文化。新石器房址共 8 座，分在两期里。早期类型是带外伸门道的半地穴房址。另有 3 座墓，期属分不清，随葬很少，所以不放进这个场景。点位用和龙市中心。": "In Helong Xingcheng, phases I and II are Neolithic. The bronze-age Xingcheng culture is phases III to V. Eight Neolithic houses are split across the two phases. The early type is a pit house with an extended entry. Three graves have unclear phases and few grave goods, so they are left out of this scene. The dot is the Helong center.",
  "青铜时代": "Bronze Age",
  "火与金属的新篇章": "A new chapter of fire and metal",
  "青铜文明 · 区域交流": "Bronze culture · regional contact",
  "石范、青铜器与陶器，串起更加复杂的生产、聚落与交流网络。": "Stone molds, bronzes, and pottery, linking a more complex web of making, settlement, and contact.",
  "双辽市": "Shuangliao",
  "石器、陶器、铜刀与铜饰": "Stone, pottery, copper knives, and copper ornaments",
  "位于双辽东明一带，点位用双辽市中心。2007 年墓地出土铜器 109 件，有刀、扣、锥、饰件。这批材料里没有铜范。": "Around Dongming in Shuangliao. The dot is the city center. The 2007 cemetery yielded 109 copper objects: knives, buttons, awls, and ornaments. This material has no copper molds.",
  "汉书": "Hanshu",
  "大安市": "Da'an",
  "陶铜铁器、青铜范": "Pottery, copper, iron, and bronze molds",
  "月亮泡一带，点位用大安市中心。遗址从夏到西汉早期，汉书文化为战国至西汉初。": "Around Yueliangpao. The dot is the Da'an center. The site runs from the Xia into the early Western Han. Hanshu culture is Warring States to early Western Han.",
  "01 / 旧石器时代": "01 / Paleolithic",
  "桦甸地区 · 概念场景，非遗址实测复原": "Huadian area · a concept scene, not a measured reconstruction",
  "首个立体场景": "First spatial scene",
  "走进寿山仙人洞": "Enter Shoushan Xianrendong",
  "洞穴 · 石器 · 动物遗存": "Cave · stone tools · animal remains",
  "进入寿山仙人洞立体场景": "Enter the Shoushan Xianrendong scene",
  "寿山仙人洞概念场景": "Shoushan Xianrendong concept scene",
  "寿山仙人洞立体场景：洞穴、树木、石器和动物骨骼示意": "Shoushan Xianrendong scene: a cave, trees, stone tools, and animal bone, shown as a guide",
  "发现洞穴里的生活线索": "Traces of life in the cave",
  "一处栖居，三种线索": "One shelter, three clues",
  "先看洞穴，再靠近石器和动物遗存。点一下场景里的物件，可以读一句说明。": "Look at the cave first, then move closer to the stone tools and animal remains. Tap an object to read one line.",
  "本场景依据用户看展资料第 1–2 页": "This scene follows pages 1–2 of the visit notes",
  "洞穴环境": "Cave setting",
  "可供栖居的天然空间": "A natural space that could be lived in",
  "资料记载寿山仙人洞发现了旧石器和动物骨骼。洞穴造型用于表达这一生活环境，尚未依据测绘资料复原。": "The notes say Shoushan Xianrendong yielded Paleolithic tools and animal bone. The cave shape expresses that setting. It is not rebuilt from a survey.",
  "资料第 1 页 · 仙人洞遗址": "Notes page 1 · Xianrendong",
  "打制石器": "Chipped stone",
  "从石核到石片": "From core to flake",
  "点击观察石核与石片的体积关系。石核是取料的母体，薄片经打击剥落后可以进一步加工成工具。此处为工艺示意，未对应某一件出土器物。": "Tap to compare the core and the flakes. The core is the parent stone. Thin flakes struck from it can be worked into tools. This shows the method, not one excavated object.",
  "资料第 2 页 · 石器加工技法": "Notes page 2 · how stone was worked",
  "动物遗存": "Animal remains",
  "考古现场留下的线索": "Clues left at the dig",
  "动物骨骼是资料提到的发现之一，可帮助理解古环境与人类活动。图中骨骼为通用示意，不推定动物种类，也不单凭骨骼认定狩猎行为。": "Animal bone is one of the finds in the notes. It helps with the ancient setting and human activity. The bones drawn here are generic. They do not name a species, and bone alone does not prove hunting.",
  "资料第 1 页 · 石器与动物骨骼": "Notes page 1 · stone tools and animal bone",
  "洞口": "Cave mouth",
  "寿山仙人洞发现过旧石器和动物骨骼。这个洞口是环境示意，没有按测绘复原。": "Paleolithic tools and animal bone were found at Shoushan Xianrendong. This mouth is a setting, not a surveyed reconstruction.",
  "石核与石片": "Core and flakes",
  "寿山仙人洞的石核是打下石片的母体，薄片再修才能成器。眼前这组是技法示意，对不上某一件出土石器。": "A Shoushan core is the parent from which flakes were struck. A thin flake still had to be retouched into a tool. This group shows the method. It is not one excavated piece.",
  "动物骨骼": "Animal bone",
  "寿山仙人洞里有动物骨骼，可以看当时的环境和人的活动。这几根是通用示意，看不出是哪种动物。": "There is animal bone in Shoushan Xianrendong. It speaks to the setting and to human activity. These pieces are generic. They do not show which animal.",
  "02 / 新石器时代": "02 / Neolithic",
  "农安地区 · 概念场景，非遗址实测复原": "Nong'an area · a concept scene, not a measured reconstruction",
  "新石器立体场景": "Neolithic spatial scene",
  "走进左家山": "Enter Zuojia Shan",
  "房址 · 石龙 · 陶器": "House · stone dragon · pottery",
  "进入左家山立体场景": "Enter the Zuojia Shan scene",
  "左家山概念场景": "Zuojia Shan concept scene",
  "左家山立体场景：一座房址、石灰岩石龙和陶器示意": "Zuojia Shan scene: a house floor, a limestone dragon, and pottery, shown as a guide",
  "沿着水系安家的线索": "Clues of settling along the water",
  "一座房，一条石龙": "One house, one stone dragon",
  "先看房址的轮廓，再靠近石龙和陶器。点一下物件可以读一句说明。": "Look at the house outline first, then move closer to the stone dragon and the pottery. Tap an object to read one line.",
  "吉林省地方志 · 左家山遗址": "Jilin gazetteer · Zuojia Shan",
  "房址": "House floor",
  "方形房、柱洞、门道和灶": "A square house, postholes, an entry, and a hearth",
  "左家山的房子是方形或圆角长方形，有柱洞、门道和灶。这一座只示意这些部分，没有复原平面。": "Zuojia Shan houses are square or rounded rectangles, with postholes, an entry, and a hearth. This one only points at those parts. It does not restore the plan.",
  "石龙": "Stone dragon",
  "石灰岩质，出在二期": "Limestone, from phase II",
  "左家山二期出过一件石灰岩质石龙。这条是按类别做的示意，没有对照原件的尺寸和纹样。": "Phase II at Zuojia Shan yielded one limestone dragon. This one follows the type. It does not match the original size or carving.",
  "吉林省地方志 · 左家山二期": "Jilin gazetteer · Zuojia Shan phase II",
  "陶器": "Pottery",
  "筒形罐和钵为主": "Mostly cylindrical jars and bowls",
  "陶器以筒形罐和钵为主，也有碗、斜口器、器座、杯和纺轮。之字纹比较常见。罐子上的线只是纹饰示意。": "Pottery is mostly cylindrical jars and bowls, also dishes, angled-mouth vessels, stands, cups, and spindle whorls. Zigzag impressions are common. The lines on the jar only suggest the pattern.",
  "左家山遗址出土陶器": "Pottery from Zuojia Shan",
  "已完成": "Done",
  "已完成 ": "Done ",
  "已点亮": "Lit",
  "可进入": "Open",
  "未解锁": "Locked",
  "文明的四个篇章": "Four chapters of the civilization",
  "查看版本与资料说明": "Version and sources",
  " 场景预览 ": " Scene preview ",
  "自由预览开": "Free preview on",
  "自由预览": "Free preview",
  "吉林省遗址分布地图，点击地块或遗址聚焦": "Map of sites in Jilin. Tap a region or a site to focus.",
  "朝鲜族自治州": "Korean Autonomous Prefecture",
  "场景载入中": "Loading the scene",
  "显示名称": "Show names",
  "放大地图": "Zoom in",
  "缩小地图": "Zoom out",
  "返回全图": "Whole map",
  "关闭详情": "Close details",
  "遗址所在地 · 区域级示意": "Where the site sits · a regional sketch",
  "地图地块": "Map region",
  "下一步场景素材 · ": "Next scene material · ",
  "完成本章": "Finish this chapter",
  "现代行政边界底图 · 遗址以县市中心示意 · 章内虚线和跨章虚线都是展示顺序，不是迁徙路线": "Modern boundaries underneath. Sites are drawn at county or city centers. Dashed lines are the order of the tour, not migration routes.",
  "资料与地图说明": "Notes on the sources and the map",
  "关闭说明": "Close notes",
  "这张地图如何阅读": "How to read this map",
  "吉林文明地图": "Map of Jilin civilization",
  "寿山仙人洞 · 示意漫游": "Shoushan Xianrendong · guided walk",
  "正在进入寿山仙人洞": "Entering Shoushan Xianrendong",
  "远景还没接上，先看示意。": "The distant world is not ready yet. Showing the sketch.",
  "层迹 STRATA · 从眼前，走进史前": "STRATA · From here into prehistory",
  "进入寿山仙人洞 →": "Enter Shoushan Xianrendong →",
  "进入左家山一期生活场景 →": "Enter the Zuojia Shan phase I living scene →",
  "左家山一期生活场景": "Zuojia Shan phase I living scene",
  "兴城二期": "Xingcheng phase II",
  "后太平": "Houtaiping",
  "洞里的石器和骨头。句子对照展牌和一九九三年发掘报告。": "Stone and bone in the cave. The lines follow the gallery label and the 1993 excavation report.",
  "一期后段的房前生活。二期石龙保留在地图资料中。": "Life in front of the phase I house. The phase II stone dragon stays in the map notes.",
  "本章观察已完成，后续将按当地资料制作可漫游场景。": "This chapter's observations are done. A walkable scene will be made from the local records.",
  "继续下一章 →": "Next chapter →",
  "四个篇章已完成，可从上方回访。": "All four chapters are done. Revisit them from above.",
  "漫游场景": "Walkable scene",
  "返回地图": "Back to the map",
  "返回观察全貌": "Back to the full view",
  "走近标记，会读到一句。句子对照博物院展牌和一九九三年发掘报告。": "Walk up to a mark and a line is read aloud. The lines follow the museum label and the 1993 excavation report.",
  "看空场景": "Empty scene",
  "放回标记": "Put the marks back",
  "生成接口": "Generation notes",
  "空场景示意。标记先拿开。环境图还没有生成，远景也还没有接上。": "An empty-scene sketch. The marks are set aside. The environment image is not generated, and the distance is not connected.",
  "已经提交": "Already submitted",
  "远景文件已回来": "The distance file is back",
  "World Labs 用的是去掉采石疤的空场景，模型是 marble-1.1。里面不要人，不要石器，不要骨头。": "World Labs used the empty scene with the quarry scar removed, model marble-1.1. No people, no stone tools, no bone.",
  "Tripo 用两张已看过的图。一件是不指定器类的石头，一件是密质骨段，松质只在断口。": "Tripo used two pictures already reviewed. One is a stone with no tool type assigned. One is a dense bone shaft, with spongy bone only at the break.",
  "石头和骨头叠在远景地面上。已入账 1640 额度。地图也还没接。": "The stone and the bone sit on the distant ground. 1,640 credits are already booked.",
  "放下": "Put it down",
  "再听": "Hear it again",
  "教学对白": "Teaching line",
  "一九九三年发掘报告": "1993 excavation report",
  "拖动环顾。W A S D 走动。": "Drag to look around. Walk with W A S D.",
  "拖动环顾。W A S D 走进洞。": "Drag to look around. Walk into the cave with W A S D.",
  "洞外是已接上的远景。": "Outside the cave, the distance view is connected.",
  "空场景。洞里还没有标记。拖动环顾，W A S D 走进洞。": "Empty scene. No marks in the cave yet. Drag to look around, and walk in with W A S D.",
  "地点": "Place",
  "石制品": "Stone artifacts",
  "骨化石": "Fossil bone",
  "展牌写，洞在桦甸市西北约二十三公里的寿山东坡，海拔四百六十米。发掘报告写，洞口朝南偏东十二度。下层骨化石大约十六万两千一百年，上下一万八千年。上层大约三万四千二百九十年，上下五百一十年。": "The label says the cave is on the east slope of Shoushan, about 23 kilometers northwest of Huadian, at 460 meters. The excavation report says the mouth faces 12 degrees south of east. The lower bone bed is about 162,100 years, plus or minus 18,000. The upper bed is about 34,290 years, plus or minus 510.",
  "一九九三年发掘报告写，洞里出了石制品一百九十七件，以小石制品为主。": "The 1993 excavation report says the cave yielded 197 stone artifacts, mostly small ones.",
  "一九九三年报告记有打制骨器十八件、磨制骨器一件，以及许多哺乳动物化石和一些鸟类化石。种属另文再写。": "The 1993 report records 18 chipped bone tools, one ground bone tool, many mammal fossils, and some bird fossils. The species are written up elsewhere.",
  "正在进入左家山一期": "Entering Zuojia Shan phase I",
  "Esc 返回地图": "Esc returns to the map",
  "近景试排 v7 · 走近房址触发人物讲解": "Near-field trial v7 · walk up to the house and she speaks",
  "查看陶罐介绍": "About the pot",
  "了解方形房址": "About the square house",
  "屋里的人": "The person in the house",
  "正在起身": "Standing up",
  "正在走近": "Walking over",
  "正在说": "Speaking",
  "她从屋子那边朝你走过来。": "She is walking over from the house.",
  "声音还没准备好，先看字幕": "The voice is not ready. Read the line.",
  "说完了 · 可以再问": "She finished · you can ask again",
  "声音没响，字幕还在": "No sound. The line is still here.",
  "点一下再听，浏览器拦住了自动出声": "Tap to hear it. The browser blocked autoplay.",
  "声音没载入，先看字幕": "The voice did not load. Read the line.",
  "她在想": "She is thinking",
  "这句没接上": "That line did not connect",
  "这句没送到她那边。你再问一次。": "That question did not reach her. Ask once more.",
  "声音停了 · 可以再听": "The voice stopped · you can hear it again",
  "你想问她一句": "Ask her one thing",
  "问屋里的人": "Ask the person in the house",
  "问她": "Ask her",
  "再听一遍": "Hear it again",
  "停止": "Stop",
  "按地方志预设编的第一人称对白，不是古人原话。声音是现在的晓晓轻声。口型仍是示意张合。": "A first-person line written from the gazetteer. Not words from the past. The voice is a present-day speaker. The mouth only opens and closes.",
  "拖动环视 · WASD / 方向键行走 · 靠近房屋或陶罐点击查看": "Drag to look · WASD or arrow keys to walk · move close and tap the house or the pot",
  "开启环境声 ♫": "Ambient sound on ♫",
  "关闭环境声 ♫": "Ambient sound off ♫",
  "当前浏览器无法播放环境声。": "This browser cannot play the ambient sound.",
  "手制筒形陶罐": "Hand-built cylindrical pot",
  "关闭介绍": "Close",
  "一期类型示意 · 非原器扫描": "A phase I type, not a scan of the original",
  "摆放位置为教学示意，不是考古出土原位；提示音与环境声也不是史前录音。": "The placement is for teaching, not the excavated spot. The cues and ambient sound are not prehistoric recordings.",
  "方形柱洞房址 · 上部结构推测": "Square posthole house · the upper part is a guess",
  "吉林省地方志记载左家山一期后段的 1 号房址平面呈方形，有 8 个柱洞，房内发现沙质灰褐陶器、骨针和骨锥等。一期后段的一项碳十四测年为距今 6,755±115 年，但不是这栋房屋每一根柱子的直接年代。眼前可触摸的屋顶、墙面和入口形态是视觉补全，现有资料不能确认它们原来长什么样。陶罐、枝材与骨器的摆放也不是出土原位；鱼骨和蚌壳见于全遗址资料，不能直接锁定在这座一期房屋门前。": "The Jilin gazetteer says phase I house 1 at Zuojia Shan has a square plan and 8 postholes. Inside were sandy gray-brown pottery, a bone needle, and a bone awl. One radiocarbon date for the later part of phase I is 6,755±115 years ago. It is not a date for every post. The roof, walls, and entrance you can walk up to are filled in by eye. The records do not confirm how they looked. The pot, branches, and bone tools are not in their excavated places. Fish bone and shell appear in the site records as a whole, and cannot be pinned in front of this phase I house.",
  "模型、生活痕迹的位置和衣着想象均属教学推测；房址比例仍待原发掘图版复核。": "The model, the placement of daily traces, and the clothing are teaching guesses. The house scale still needs the original excavation drawings.",
  "地方志记载，左家山一期出土过手制的沙质灰褐陶筒形罐，可见刻划弦纹、席纹和压印“之”字纹。一期后段有一项碳十四测年为距今 6,755±115 年；这是文化层的测年线索，不是给眼前这件模型或某个陶罐单独测得的年龄。制作和使用它的人属于当时在伊通河台地活动的居民，现有材料不能确定个人身份。陶罐可能用于盛放、处理日常物资，但某件器物的具体用途尚需残留物和使用痕迹等证据。它让我们看见当时已有手工制陶及较稳定的居住活动；不能仅凭器形推断仪式意义。这个 Tripo 模型是类型示意，不是出土原器扫描，摆放位置也不是出土原位。": "The gazetteer says phase I at Zuojia Shan yielded hand-built sandy gray-brown cylindrical pots, with incised string marks, mat marks, and impressed zigzag. One radiocarbon date for the later part of phase I is 6,755±115 years ago. That dates the layer, not this model or one pot. The people who made and used them lived on the Yitong terrace. The records do not name anyone. A pot may have held or processed daily goods. What one vessel did still needs residues and wear. It shows hand-built pottery and a fairly settled life. Shape alone does not prove a ritual. This Tripo model is a type, not a scan of the excavated pot, and it is not in the excavated place.",
  "地方志 ↗": "Gazetteer ↗",
  "正在读取已经做好的世界": "Reading the world that is already made",
  "正在铺开河岸": "Laying out the riverbank",
  "正在放上房屋和人": "Setting down the house and the person",
  "可以走进去了": "You can walk in",
  "世界还没就绪。按 Esc 回地图。": "The world is not ready. Press Esc to return to the map.",
  "场景没铺开。按 Esc 回地图。": "The scene did not open. Press Esc to return to the map.",
  "你走近了。我在这方屋子里，针还捏在手里。": "You came closer. I am in this square house, the needle still in my hand.",
  "长春": "Changchun",
  "吉林": "Jilin City",
  "四平": "Siping",
  "辽源": "Liaoyuan",
  "通化": "Tonghua",
  "白山": "Baishan",
  "松原": "Songyuan",
  "白城": "Baicheng",
  "延边": "Yanbian",
  "靶山墓群": "Bashan cemetery",
  "灶": "Hearth",
  "左家山房址里有灶。这个圆圈只标出灶的位置。": "The Zuojia Shan houses had a hearth. This circle only marks where it was.",
  "吉林省地方志 · 左家山房址": "Jilin gazetteer · Zuojia Shan houses",
  "左家山的陶器以筒形罐和钵为主，也有碗、斜口器、器座、杯和纺轮。之字纹比较常见。罐子上的线只是纹饰示意。": "Zuojia Shan pottery is mostly cylindrical jars and bowls, also dishes, angled-mouth vessels, stands, cups, and spindle whorls. Zigzag impressions are common. The lines on the jar only suggest the pattern.",
  "03 / 新石器晚期": "03 / Late Neolithic",
  "和龙地区 · 概念场景，非遗址实测复原": "Helong area · a concept scene, not a measured reconstruction",
  "晚期聚落场景": "Late settlement scene",
  "走进兴城二期": "Enter Xingcheng phase II",
  "聚落 · 房址 · 器物": "Settlement · houses · objects",
  "进入兴城二期立体场景": "Enter the Xingcheng phase II scene",
  "兴城二期概念场景": "Xingcheng phase II concept scene",
  "兴城二期立体场景：带外伸门道的半地穴聚落示意": "Xingcheng phase II scene: a settlement of pit houses with extended entries, shown as a guide",
  "先看聚落的轮廓": "Start with the shape of the settlement",
  "一群带门道的房子": "A cluster of houses with entries",
  "先看聚落的轮廓，再靠近一座房和器物。报告里的 3 座墓期属分不清，随葬也少，所以没有放进这个二期场景。": "Look at the settlement outline first, then move closer to one house and the objects. The report's 3 graves have unclear phases and few grave goods, so they are not in this phase II scene.",
  "《和龙兴城》报告所述": "As described in Helong Xingcheng",
  "聚落": "Settlement",
  "房子聚在一起": "Houses grouped together",
  "《和龙兴城》记新石器房址共 8 座，分在一期和二期。早期那种是带外伸门道的半地穴。画面上的几座只表示聚落形态，报告里的 8 座分属两个阶段。": "Helong Xingcheng records 8 Neolithic houses, split between phases I and II. The early kind is a pit house with an extended entry. The few in the picture only show the settlement form. The report's 8 belong to two stages.",
  "《和龙兴城》· 新石器房址": "Helong Xingcheng · Neolithic houses",
  "半地穴和外伸门道": "Pit house and extended entry",
  "早期类型是带外伸门道的半地穴房址。靠近这一座，能看到下凹的居住面、门道和柱子。这些都是示意，对不上某一座发掘房址。": "The early type is a pit house with an extended entry. Move closer to see the sunken floor, the entry, and the posts. All of it is a guide and matches no single excavated house.",
  "《和龙兴城》· 房址形制": "Helong Xingcheng · house form",
  "器物": "Objects",
  "陶器和石骨器": "Pottery, stone, and bone tools",
  "这一章记有陶器，也提到石骨器。罐、石块和骨器都是类别示意。": "This chapter records pottery and mentions stone and bone tools. The jar, the stone, and the bone tool only show the categories.",
  "新石器晚期章 · 兴城二期": "Late Neolithic chapter · Xingcheng phase II",
  "兴城二期。《和龙兴城》记新石器房址共 8 座，分在一期和二期。早期那种是带外伸门道的半地穴。画面上的几座只表示聚落形态，报告里的 8 座分属两个阶段。": "Xingcheng phase II. Helong Xingcheng records 8 Neolithic houses, split between phases I and II. The early kind is a pit house with an extended entry. The few in the picture only show the settlement form. The report's 8 belong to two stages.",
  "半地穴房": "Pit house",
  "兴城二期的早期类型是带外伸门道的半地穴房址。这一座能看到下凹的居住面和门道。都是示意，对不上某一座发掘房址。": "The early Xingcheng type is a pit house with an extended entry. This one shows the sunken floor and the entry. It is a guide and matches no single excavated house.",
  "兴城二期这一章记有陶器。这件罐子是器类示意。": "This Xingcheng phase II chapter records pottery. This jar only shows the type.",
  "兴城二期条目": "Xingcheng phase II entry",
  "石器": "Stone tools",
  "兴城二期章里提到石骨器。这块石头只表示石器，对不上某一件出土物。": "The Xingcheng phase II chapter mentions stone and bone tools. This stone only stands for a stone tool and matches no single find.",
  "新石器晚期章引言": "Late Neolithic chapter introduction",
  "骨器": "Bone tools",
  "兴城二期把骨器和石器记在一起。这根是器类示意，对不上某一件出土物。": "Xingcheng phase II records bone tools together with stone tools. This piece only shows the type and matches no single find.",
  "04 / 青铜时代": "04 / Bronze Age",
  "双辽地区 · 概念场景，非遗址实测复原。资料记为东明一带，点位仍用双辽市中心示意": "Shuangliao area · a concept scene, not a measured reconstruction. The records say around Dongming. The dot still uses the Shuangliao center.",
  "青铜时代场景": "Bronze Age scene",
  "走进后太平": "Enter Houtaiping",
  "石器 · 陶器 · 铜器": "Stone · pottery · copper",
  "进入后太平立体场景": "Enter the Houtaiping scene",
  "后太平概念场景": "Houtaiping concept scene",
  "后太平立体场景：石器、陶器和铜刀、铜扣、铜锥、饰件示意": "Houtaiping scene: stone tools, pottery, and copper knives, buttons, awls, and ornaments, shown as a guide",
  "石器、陶器和铜器": "Stone, pottery, and copper",
  "先看石器，再靠近陶器和铜器。2007 年墓地的铜器有刀、扣、锥、饰件。材料里没有铜范。": "Look at the stone tools first, then move closer to the pottery and copper. The 2007 cemetery copper includes knives, buttons, awls, and ornaments. The material has no copper molds.",
  "后太平墓地发掘材料": "Houtaiping cemetery excavation material",
  "和铜器记在一起": "Recorded together with copper",
  "后太平的材料里有石器。这几块是器类示意。材料只写了石器，没有写加工方法。": "The Houtaiping material includes stone tools. These pieces only show the type. The material names stone tools but not how they were made.",
  "后太平遗址": "Houtaiping site",
  "和石器、铜器同出": "Found with stone and copper",
  "陶器和石器、铜器一起出土。罐和钵只表示器类。": "Pottery was found with stone and copper. The jar and bowl only show the types.",
  "铜器": "Copper",
  "刀、扣、锥、饰件": "Knives, buttons, awls, ornaments",
  "2007 年墓地出土铜器 109 件，其中有刀、扣、锥、饰件。眼前这几件只按类别示意。": "The 2007 cemetery yielded 109 copper objects, including knives, buttons, awls, and ornaments. These pieces only show the categories.",
  "2007 年后太平墓地": "2007 Houtaiping cemetery",
  "后太平的材料里有石器。这几块是器类示意。": "The Houtaiping material includes stone tools. These pieces only show the type.",
  "后太平的陶器和石器、铜器一起出土。罐和钵只表示器类。": "Houtaiping pottery was found with stone and copper. The jar and bowl only show the types.",
  "铜刀": "Copper knife",
  "2007 年墓地出土铜器 109 件，其中有刀。这一把是示意。": "The 2007 cemetery yielded 109 copper objects, knives among them. This one is a guide.",
  "铜扣": "Copper button",
  "同一批铜器里有扣。这枚圆片只表示扣。": "The same copper group includes buttons. This disk only stands for a button.",
  "铜锥": "Copper awl",
  "铜锥和刀、扣、饰件记在一起。这根是示意。": "Copper awls are recorded with the knives, buttons, and ornaments. This one is a guide.",
  "饰件": "Ornament",
  "饰件没有更细的形状记录。这块小片只占一个示意的位置。": "The ornaments have no finer record of shape. This small piece only holds the place.",
  "AI 示意": "AI sketch",
  "循迹吉林": "Tracing Jilin",
  "从一片土地，走进一段文明": "From a piece of land into a civilization",
  "北 N": "N",
  "展示顺序": "Tour order",
  "锁": "Locked",
  "未解锁 ·": "Locked ·",
  "本章关联地区": "Regions in this chapter",
  "其他地区": "Other regions",
  "章内顺序": "Order in chapter",
  "切换遗址名称": "Toggle site names",
  "隐藏名称": "Hide names",
  "当前地块沿用现代市州边界，用于组织画面，不代表史前文化的分布边界。": "Regions use modern city and prefecture borders to organize the view. They are not prehistoric culture boundaries.",
  "可进入概念场景 ·": "Concept scene open ·",
  "返回省域地图": "Back to the province map",
  "本章已完成": "Chapter done",
  "观察三处后完成": "Finish after three observations",
  "内容依据你提供的《吉林省博物院看展资料》，当前章节对应第": "The content follows your Jilin Provincial Museum visit notes. This chapter is on page",
  "页。": ".",
  "边界来自阿里云 DataV 的吉林省 GeoJSON，采用现代市州边界，不表达史前文化疆界。": "Borders come from the Aliyun DataV GeoJSON for Jilin. They are modern city and prefecture borders, not prehistoric culture boundaries.",
  "所有点位均采用所属县市中心作区域级示意。精确坐标需逐址核验。": "Every dot sits at its county or city center as a regional guide. Exact coordinates need checking site by site.",
  "腰岭子在长春市九台区西营城镇西部、石头口门村北，点位用九台区中心。长岭腰井子是另一处遗址。元宝沟用农安县中心，大六道沟用珲春市中心，聚宝山用镇赉县中心。立新、金台仍不落点。": "Yaolingzi is west of Xiyingcheng Town in Jiutai, Changchun, north of Shitoukoumen village. Its dot uses the Jiutai center. Changling Yaojingzi is another site. Yuanbaogou uses the Nong'an center, Daliudaogou the Hunchun center, and Jubaoshan the Zhenlai center. Lixin and Jintai still have no dot.",
  "虚线是展示顺序，不代表实际迁徙、文化传播或旅游路线。时代顺序与地理位置分开表达。": "Dashed lines are the tour order, not migration, cultural spread, or travel routes. Time order and geography are shown separately.",
  "四个概念场景都是 AI 画面示意：寿山仙人洞、左家山、兴城二期、后太平。点画面里的物件才记下观察。看过三处，再点「完成本章」，下一章才打开。拖动只是平移这张平面图，不是转三维模型。": "All four concept scenes are AI sketches: Shoushan Xianrendong, Zuojia Shan, Xingcheng phase II, and Houtaiping. An observation counts only when you tap an object in the picture. After three, tap Finish this chapter to open the next one. Dragging only pans the flat picture. It does not turn a 3D model.",
  "地址加上 ?free=1，或点顶栏「自由预览」，可以不按顺序翻阅。这是验收用的，默认参观仍然上锁。": "Add ?free=1 to the address, or tap Free preview at the top, to browse out of order. This is for review. A normal visit stays locked.",
  "回到场景全貌": "Back to the whole scene",
  "查看地图数据来源": "Map data source",
  "查看 D3 地图处理方法": "How the D3 map is drawn",
  "AI 画面示意 · 拖动是平移": "AI sketch · drag to pan",
  "寿山仙人洞 AI 画面示意。拖动平移画面，点洞口、石器或骨骼。": "Shoushan Xianrendong AI sketch. Drag to pan, then tap the mouth, the stone tools, or the bone.",
  "左家山 AI 画面示意。点房址、石龙或陶器。": "Zuojia Shan AI sketch. Tap the house, the stone dragon, or the pottery.",
  "兴城二期 AI 画面示意。点房子或器物。": "Xingcheng phase II AI sketch. Tap a house or an object.",
  "后太平 AI 画面示意。点石器、陶器或铜器。没有铜范。": "Houtaiping AI sketch. Tap the stone, the pottery, or the copper. There are no copper molds."
};

export const patterns = [
  [/^已观察 (\d+) \/ 3$/, "Seen $1 / 3"],
  [/^请先完成上一章「(.+)」：看过三处观察，再点「完成本章」。$/, "Finish the previous chapter, “$1”, first: view the three observations, then tap Finish this chapter."],
  [/^未解锁 · (.+)$/, "Locked · $1"],
  [/^查看(.+)地块$/, "View the $1 region"],
  [/^(.+)未解锁$/, "$1 is locked"],
  [/^前往(.+)$/, "Go to $1"],
  [/^查看(.+)$/, "View $1"],
  [/^进入(.+) →$/, "Enter $1 →"],
  [/^(.+) · 3D 漫游筹备中$/, "$1 · 3D walk still in preparation"],
  [/^你问，(.+)。$/, "You asked, $1."],
  [/^走近了「(.+)」。句子在牌上。也可按 E。$/, "Close to “$1”. The line is on the card. You can also press E."]
];

export function translate(value) {
  if (typeof value !== "string" || !/[\u4e00-\u9fff]/.test(value)) return null;
  if (Object.prototype.hasOwnProperty.call(exact, value)) return exact[value];
  const trimmed = value.trim();
  if (trimmed !== value && Object.prototype.hasOwnProperty.call(exact, trimmed)) {
    return value.replace(trimmed, exact[trimmed]);
  }
  for (const [re, tpl] of patterns) {
    const match = value.match(re);
    if (!match) continue;
    return tpl.replace(/\$(\d+)/g, (_, index) => {
      const part = match[index];
      return Object.prototype.hasOwnProperty.call(exact, part) ? exact[part] : part;
    });
  }
  return null;
}

export const voices = {
  zh: {name: "zh-CN-XiaoxiaoNeural", style: "", rate: "-12%", pitch: "-2st", xmlLang: "zh-CN"},
  en: {name: "en-US-AriaNeural", style: "", rate: "-8%", pitch: "-1st", xmlLang: "en-US"}
};

export const guideLinesEn = [
  {id: "opening", ask: "", text: "You came closer. I am in this square house, the needle still in my hand. Eight postholes ring me, and the river beach is outside. I cannot say what the roof used to be."},
  {id: "house", ask: "How did you live in this house", text: "The floor is square. Posts stood in eight holes. People slept and worked in this square. Nobody can say what covered the top."},
  {id: "pot", ask: "What was the pot for", text: "A hand-built gray-brown pot, with string marks, mat marks, and zigzag impressions. Water or grain, the pot does not tell me."},
  {id: "winter", ask: "How did you get through winter", text: "When it was cold we crowded toward the posts. The needle still had to sew, and the awl still had to drill. How cold that one winter was, nobody wrote down."}
];

export const shoushanLines = {
  place: {title: "地点", line: "展牌写，洞在桦甸市西北约二十三公里的寿山东坡，海拔四百六十米。发掘报告写，洞口朝南偏东十二度。下层骨化石大约十六万两千一百年，上下一万八千年。上层大约三万四千二百九十年，上下五百一十年。"},
  tools: {title: "石制品", line: "一九九三年发掘报告写，洞里出了石制品一百九十七件，以小石制品为主。"},
  bone: {title: "骨化石", line: "一九九三年报告记有打制骨器十八件、磨制骨器一件，以及许多哺乳动物化石和一些鸟类化石。种属另文再写。"}
};

export function shoushanSpeech(id, lang) {
  const item = shoushanLines[id];
  if (!item) return "";
  return lang === "en" ? exact[item.line] : item.line;
}
